language: php
php:
    - '7.0'
    - '7.1'
    - '7.2'
services:
    - postgresql
install:
    - composer install
before_script:
    - psql -c 'create database pgi_test;' -U postgres
    - psql -U postgres -d pgi_test -1 -f pgi_test.sql
notifications:
  slack:
    rooms:
      - secure: gkz+hz9QGqBkxp436dTfyYxhgaYmLJxQEWbV9iyoMTCaEazAS/8rDPSxXtF6dtJ9KnjOztpmQ0rNj+YxYhksIkTXhFAFJZVl/T+NauCLNCKRgNnC/QsLD4EC0r/oilbUzMo9eucc5In3oY5PSjj9qRaqtNQPiE+BNDyI/2P9ryw=
