language: php
php:
    - '7.0'
    - '7.1'
    - '7.2'
services:
    - postgresql
install:
    - composer install
before_script:
    - psql -c 'create database pgi_test;' -U postgres
    - psql -U postgres -d pgi_test -1 -f pgi_test.sql
notifications:
  slack:
    rooms:
      - secure: d2zqCiSp3auqg6U/Fy9YBPAvCd3u/XKwWGQbRBvdSKaDmPN7cedWDIfxJB36angbUYzSCSN5kbt7vxCe4hjSKU1R4vTCunpWnCJ6jbaHIk01s9DSYE8juNbE3I7om7bsl6SNWg79/uI0o1T6WiC3uauYJDRo7qeC7QpCqqIBM08=
